#ifndef CORE_OPCODES_H
#define CORE_OPCODES_H

#define C2S_CONNECT 0
#define S2C_ACCEPT_ACT 0
#define S2C_DISCONNECT 1
#define C2S_HEARTBEAT 2
#define S2C_HEARTBEAT 2

#define HEART_BEAT_INTERVAL 6000
#endif
